import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { ChatSwarmError, MAX_PROMPT_BYTES, MAX_RESULT_BYTES } from "./chat-swarm-contract.js";
import { ChatSwarmStore } from "./chat-swarm-store.js";

function fixture() { const root = mkdtempSync(join(tmpdir(), "devspace-chat-swarm-")); const store = new ChatSwarmStore(root); const swarm = store.createSwarm({ ownerIdentity: "owner", workerLimit: 2 }); const worker = store.createWorker({ swarmId: swarm.id, label: "peer", runtimeKind: "mcp_peer" }); return { root, store, swarm, worker }; }
function cleanup(f: { root: string; store?: ChatSwarmStore }) { f.store?.close(); rmSync(f.root, { recursive: true, force: true }); }

test("create/load swarm and worker never persist raw credential", () => { const f = fixture(); try { assert.equal(f.store.getSwarm(f.swarm.id)?.inviteCredentialHash, undefined); assert.equal(f.store.getWorker(f.worker.id)?.runtimeKind, "mcp_peer"); assert.equal(f.swarm.ownerIdentityFingerprint, f.store.getSwarm(f.swarm.id)?.ownerIdentityFingerprint); const limited = f.store.createSwarm({ ownerIdentity: "owner-2", workerLimit: 1 }); f.store.createWorker({ swarmId: limited.id, label: "only", runtimeKind: "mcp_peer" }); assert.throws(() => f.store.createWorker({ swarmId: limited.id, label: "overflow", runtimeKind: "mcp_peer" }), (e: unknown) => e instanceof ChatSwarmError && e.code === "OWNERSHIP_CONFLICT"); } finally { cleanup(f); } });

test("identical replay is idempotent and changed material request conflicts", () => { const f = fixture(); try { const first = f.store.createTask({ swarmId: f.swarm.id, taskKey: "same", prompt: "hello", payload: { b: 2, a: 1 }, preferredWorkerId: f.worker.id }); const replay = f.store.createTask({ swarmId: f.swarm.id, taskKey: "same", prompt: "hello", payload: { a: 1, b: 2 }, preferredWorkerId: f.worker.id }); assert.equal(replay.created, false); assert.equal(replay.task.id, first.task.id); assert.throws(() => f.store.createTask({ swarmId: f.swarm.id, taskKey: "same", prompt: "changed" }), (e: unknown) => e instanceof ChatSwarmError && e.code === "REPLAY_CONFLICT"); } finally { cleanup(f); } });

test("claim ownership, wrong worker rejection, and one active task per worker", () => { const f = fixture(); const other = f.store.createWorker({ swarmId: f.swarm.id, label: "other", runtimeKind: "mcp_peer" }); try { const task = f.store.createTask({ swarmId: f.swarm.id, taskKey: "one", prompt: "p" }).task; f.store.claimTask(task.id, f.worker.id); assert.throws(() => f.store.submitResult(task.id, other.id, "x"), (e: unknown) => e instanceof ChatSwarmError && e.code === "OWNERSHIP_CONFLICT"); const second = f.store.createTask({ swarmId: f.swarm.id, taskKey: "two", prompt: "p" }).task; assert.throws(() => f.store.claimTask(second.id, f.worker.id), (e: unknown) => e instanceof ChatSwarmError && e.code === "OWNERSHIP_CONFLICT"); assert.equal(f.store.getTask(second.id)?.lifecycleState, "QUEUED"); assert.equal(f.store.getWorker(f.worker.id)?.currentTaskId, task.id); } finally { cleanup(f); } });

test("RESULT_READY releases worker while retaining immutable result until collect", () => { const f = fixture(); try { const task = f.store.createTask({ swarmId: f.swarm.id, taskKey: "one", prompt: "p" }).task; f.store.claimTask(task.id, f.worker.id); f.store.startTask(task.id, f.worker.id); const ready = f.store.submitResult(task.id, f.worker.id, "done"); assert.equal(ready.lifecycleState, "RESULT_READY"); assert.equal(f.store.submitResult(task.id, f.worker.id, "done").result, "done"); assert.equal(f.store.getWorker(f.worker.id)?.currentTaskId, undefined); const next = f.store.createTask({ swarmId: f.swarm.id, taskKey: "two", prompt: "p" }).task; assert.equal(f.store.claimTask(next.id, f.worker.id).assignedWorkerId, f.worker.id); assert.throws(() => f.store.submitResult(task.id, f.worker.id, "changed"), (e: unknown) => e instanceof ChatSwarmError && e.code === "TERMINAL_IMMUTABLE"); assert.equal(f.store.getTask(task.id)?.result, "done"); assert.equal(f.store.collectTask(task.id).lifecycleState, "COLLECTED"); assert.equal(f.store.collectTask(task.id).lifecycleState, "COLLECTED"); } finally { cleanup(f); } });

test("restart converts possibly started work to reconciliation but keeps queued work queued", () => { const f = fixture(); let queuedId: string; let runningId: string; try { queuedId = f.store.createTask({ swarmId: f.swarm.id, taskKey: "queued", prompt: "q" }).task.id; runningId = f.store.createTask({ swarmId: f.swarm.id, taskKey: "running", prompt: "r" }).task.id; f.store.claimTask(runningId, f.worker.id); f.store.startTask(runningId, f.worker.id); const attempt = f.store.listAttempts(runningId)[0]!; f.store.close(); f.store = new ChatSwarmStore(f.root); assert.equal(f.store.getTask(runningId)?.lifecycleState, "RUNNING"); f.store.recoverAfterRestart(); assert.equal(f.store.getTask(queuedId)?.lifecycleState, "QUEUED"); assert.equal(f.store.getTask(runningId)?.lifecycleState, "RECONCILE_REQUIRED"); assert.throws(() => f.store.claimTask(runningId, f.worker.id), (e: unknown) => e instanceof ChatSwarmError && e.code === "RECONCILIATION_REQUIRED"); assert.throws(() => f.store.resolveReconciliation(runningId, "REQUEUE"), (e: unknown) => e instanceof ChatSwarmError && e.code === "RECONCILIATION_REQUIRED"); assert.equal(f.store.resolveReconciliation(runningId, "REQUEUE", undefined, { taskId: runningId, attemptId: attempt.id, disposition: "NO_EFFECT", evidenceRef: "restart-probe-1" }).lifecycleState, "QUEUED"); } finally { cleanup(f); } });

test("migration is idempotent and payload boundaries are enforced", () => { const f = fixture(); try { const sqlite = (f.store as unknown as { sqlite: { prepare: (sql: string) => { get: () => { version: number } } } }).sqlite; assert.equal(sqlite.prepare("select max(version) as version from devspace_schema_migrations").get().version, 17); const prompt = f.store.createTask({ swarmId: f.swarm.id, taskKey: "max", prompt: "x".repeat(MAX_PROMPT_BYTES) }).task; f.store.claimTask(prompt.id, f.worker.id); assert.equal(f.store.submitResult(prompt.id, f.worker.id, "x".repeat(MAX_RESULT_BYTES)).result?.length, MAX_RESULT_BYTES); const overflow = f.store.createTask({ swarmId: f.swarm.id, taskKey: "overflow", prompt: "p" }).task; f.store.claimTask(overflow.id, f.worker.id); assert.throws(() => f.store.submitResult(overflow.id, f.worker.id, "x".repeat(MAX_RESULT_BYTES + 1)), ChatSwarmError); f.store.close(); f.store = new ChatSwarmStore(f.root); f.store.recoverAfterRestart(); assert.equal(f.store.getTask(overflow.id)?.lifecycleState, "RECONCILE_REQUIRED"); } finally { cleanup(f); } });

test("unknown persisted task state fails closed", () => { const f = fixture(); try { const sqlite = (f.store as unknown as { sqlite: { prepare: (sql: string) => { run: (...args: unknown[]) => void } } }).sqlite; const task = f.store.createTask({ swarmId: f.swarm.id, taskKey: "corrupt", prompt: "p" }).task; sqlite.prepare("update chat_swarm_tasks set lifecycle_state=? where id=?").run("CORRUPT", task.id); assert.throws(() => f.store.getTask(task.id), (e: unknown) => e instanceof ChatSwarmError && e.code === "INVALID_STATE"); } finally { cleanup(f); } });

test("two open stores do not recover live work until explicit recovery", () => { const f = fixture(); const second = new ChatSwarmStore(f.root); try { const task = f.store.createTask({ swarmId: f.swarm.id, taskKey: "live", prompt: "p" }).task; f.store.claimTask(task.id, f.worker.id); f.store.startTask(task.id, f.worker.id); assert.equal(second.getTask(task.id)?.lifecycleState, "RUNNING"); second.recoverAfterRestart(); assert.equal(f.store.getTask(task.id)?.lifecycleState, "RECONCILE_REQUIRED"); } finally { second.close(); cleanup(f); } });

test("SQLite enforces replay, attempt ordinal, active ownership, and foreign keys", () => { const f = fixture(); try { const task = f.store.createTask({ swarmId: f.swarm.id, taskKey: "sql-one", prompt: "p" }).task; f.store.claimTask(task.id, f.worker.id); const sqlite = (f.store as unknown as { sqlite: { prepare: (sql: string) => { run: (...args: unknown[]) => void } } }).sqlite; assert.throws(() => sqlite.prepare("insert into chat_swarm_tasks (id,swarm_id,task_key,request_hash,prompt,payload_json,lifecycle_state,retry_safe,created_at,updated_at) values (?,?,?,?,?,?,?,?,?,?)").run("duplicate", f.swarm.id, "sql-one", "h", "p", "{}", "QUEUED", "true", "now", "now")); assert.throws(() => sqlite.prepare("insert into chat_swarm_attempts (id,task_id,attempt_number,runtime_kind,effect_state,created_at) values (?,?,?,?,?,?)").run("duplicate-attempt", task.id, 1, "mcp_peer", "CLAIMED", "now")); const second = f.store.createTask({ swarmId: f.swarm.id, taskKey: "sql-two", prompt: "p" }).task; assert.throws(() => sqlite.prepare("update chat_swarm_tasks set assigned_worker_id=?, lifecycle_state='RUNNING' where id=?").run(f.worker.id, second.id)); assert.throws(() => sqlite.prepare("insert into chat_swarm_workers (id,swarm_id,label,runtime_kind,lifecycle_state,continuation_epoch,created_at,updated_at) values (?,?,?,?,?,?,?,?)").run("bad-worker", "missing-swarm", "x", "mcp_peer", "AVAILABLE", 0, "now", "now")); } finally { cleanup(f); } });

test("stale restart evidence is rejected and corrupt JSON fails closed", () => { const f = fixture(); try { const task = f.store.createTask({ swarmId: f.swarm.id, taskKey: "stale", prompt: "p" }).task; f.store.claimTask(task.id, f.worker.id); const first = f.store.listAttempts(task.id)[0]!; f.store.recoverAfterRestart(); f.store.resolveReconciliation(task.id, "REQUEUE", undefined, { taskId: task.id, attemptId: first.id, disposition: "NO_EFFECT", evidenceRef: "first" }); f.store.claimTask(task.id, f.worker.id); f.store.recoverAfterRestart(); assert.throws(() => f.store.resolveReconciliation(task.id, "REQUEUE", undefined, { taskId: task.id, attemptId: first.id, disposition: "NO_EFFECT", evidenceRef: "stale" }), (e: unknown) => e instanceof ChatSwarmError && e.code === "RECONCILIATION_REQUIRED"); } finally { cleanup(f); } for (const corrupt of ["[]", "null", "not-json"]) { const g = fixture(); try { const task = g.store.createTask({ swarmId: g.swarm.id, taskKey: "json", prompt: "p" }).task; const sqlite = (g.store as unknown as { sqlite: { prepare: (sql: string) => { run: (...args: unknown[]) => void } } }).sqlite; sqlite.prepare("update chat_swarm_tasks set payload_json=? where id=?").run(corrupt, task.id); assert.throws(() => g.store.getTask(task.id), (e: unknown) => e instanceof ChatSwarmError && e.code === "INVALID_STATE"); } finally { cleanup(g); } } });

test("queued cancellation is terminal and claimed cancellation preserves uncertain ownership", () => { const f = fixture(); try { const queued = f.store.createTask({ swarmId: f.swarm.id, taskKey: "queued-cancel", prompt: "p" }).task; assert.equal(f.store.cancelTask(queued.id, "controller").lifecycleState, "CANCELLED"); const claimed = f.store.createTask({ swarmId: f.swarm.id, taskKey: "claimed-cancel", prompt: "p" }).task; f.store.claimTask(claimed.id, f.worker.id); assert.equal(f.store.requestCancel(claimed.id, f.worker.id).lifecycleState, "CANCEL_REQUESTED"); assert.equal(f.store.getWorker(f.worker.id)?.currentTaskId, claimed.id); assert.throws(() => f.store.closeSwarm(f.swarm.id), (e: unknown) => e instanceof ChatSwarmError && e.code === "RECONCILIATION_REQUIRED"); assert.equal(f.store.cancelTask(claimed.id, f.worker.id).lifecycleState, "CANCELLED"); } finally { cleanup(f); } });

test("atomic next claim refuses a closed swarm", () => { const f = fixture(); try { const task = f.store.createTask({ swarmId: f.swarm.id, taskKey: "closed-next", prompt: "p" }).task; const sqlite = (f.store as unknown as { sqlite: { prepare: (sql: string) => { run: (...args: unknown[]) => void } } }).sqlite; sqlite.prepare("update chat_swarms set status='CLOSED' where id=?").run(f.swarm.id); assert.equal((f.store as any).claimNextQueuedTaskAtomic(f.worker.id), undefined); assert.equal(f.store.getTask(task.id)?.lifecycleState, "QUEUED"); } finally { cleanup(f); } });

test("lease expiry parses equivalent offsets identically and rejects malformed observations", () => { const one = fixture(); const two = fixture(); try { const taskOne = one.store.createTask({ swarmId: one.swarm.id, taskKey: "lease-one", prompt: "p" }).task; one.store.claimTask(taskOne.id, one.worker.id); const taskTwo = two.store.createTask({ swarmId: two.swarm.id, taskKey: "lease-two", prompt: "p" }).task; two.store.claimTask(taskTwo.id, two.worker.id); const lease = new Date(Date.now() + 10_000).toISOString(); one.store.checkpointWorker(one.worker.id, 0, lease, {}); two.store.checkpointWorker(two.worker.id, 0, lease, {}); const sameInstant = lease.replace("Z", "+00:00"); assert.equal(one.store.expireWorkerLease(one.worker.id, lease)?.lifecycleState, "RECONCILE_REQUIRED"); assert.equal(two.store.expireWorkerLease(two.worker.id, sameInstant)?.lifecycleState, "RECONCILE_REQUIRED"); assert.throws(() => two.store.expireWorkerLease(two.worker.id, "not-a-time"), (e: unknown) => e instanceof ChatSwarmError && e.code === "INVALID_INPUT"); } finally { cleanup(one); cleanup(two); } });

test("targeted dispatch queues behind a busy worker and replays without another attempt", () => { const f = fixture(); try { const active = f.store.dispatchTaskAtomic({ swarmId: f.swarm.id, taskKey: "active", prompt: "p", preferredWorkerId: f.worker.id }); const queued = f.store.dispatchTaskAtomic({ swarmId: f.swarm.id, taskKey: "queued", prompt: "q", preferredWorkerId: f.worker.id }, 1); assert.equal(queued.lifecycleState, "QUEUED"); assert.equal(queued.assignedWorkerId, undefined); assert.equal(f.store.listAttempts(queued.id).length, 0); assert.throws(() => f.store.dispatchTaskAtomic({ swarmId: f.swarm.id, taskKey: "overflow", prompt: "p", preferredWorkerId: f.worker.id }, 1), (e: unknown) => e instanceof ChatSwarmError && e.code === "INVALID_INPUT"); assert.equal(f.store.getTaskByKey(f.swarm.id, "overflow"), undefined); const replay = f.store.dispatchTaskAtomic({ swarmId: f.swarm.id, taskKey: "queued", prompt: "q", preferredWorkerId: f.worker.id }, 0); assert.equal(replay.id, queued.id); assert.equal(f.store.listAttempts(queued.id).length, 0); assert.equal(f.store.listAttempts(active.id).length, 1); assert.throws(() => f.store.listTaskLedger(f.swarm.id, undefined, 0), (e: unknown) => e instanceof ChatSwarmError && e.code === "INVALID_INPUT"); assert.throws(() => f.store.listTaskLedger(f.swarm.id, undefined, 101), (e: unknown) => e instanceof ChatSwarmError && e.code === "INVALID_INPUT"); } finally { cleanup(f); } });

test("owner task ledger is redacted, deterministic, and traversable", () => { const f = fixture(); try { const first = f.store.createTask({ swarmId: f.swarm.id, taskKey: "a", prompt: "secret", payload: { token: "secret", session: "auth-secret" } }).task; const second = f.store.createTask({ swarmId: f.swarm.id, taskKey: "b", prompt: "p" }).task; f.store.claimTask(first.id, f.worker.id); f.store.startTask(first.id, f.worker.id); f.store.submitResult(first.id, f.worker.id, "result"); const page = f.store.listTaskLedger(f.swarm.id, undefined, 1); assert.deepEqual(page.tasks.map((task) => task.taskKey), ["a"]); assert.equal(page.tasks[0]?.resultPresent, true); assert.equal(page.tasks[0]?.resultHash?.length, 64); assert.equal(page.tasks[0]?.latestAttemptNumber, 1); assert.ok(page.tasks[0]?.latestAttemptId); assert.deepEqual(Object.keys(page.tasks[0]!).sort(), ["assignedWorkerId", "collectedAt", "completedAt", "createdAt", "lifecycleState", "latestAttemptId", "latestAttemptNumber", "preferredWorkerId", "resultHash", "resultPresent", "taskId", "taskKey", "updatedAt"].sort()); const encoded = JSON.stringify(page.tasks[0]); assert.equal(/secret|requestHash|retry|reconciliation|errorMessage|session|auth/i.test(encoded), false); assert.ok(page.nextCursor); const rest = f.store.listTaskLedger(f.swarm.id, page.nextCursor, 100); assert.deepEqual(rest.tasks.map((task) => task.taskKey), ["b"]); assert.equal(rest.nextCursor, undefined); assert.throws(() => f.store.listTaskLedger(f.swarm.id, "not-a-cursor"), (e: unknown) => e instanceof ChatSwarmError && e.code === "INVALID_INPUT"); assert.throws(() => f.store.listTaskLedger(f.swarm.id, Buffer.from(JSON.stringify({ swarmId: "foreign", createdAt: second.createdAt, taskId: second.id, rowid: 1 })).toString("base64url")), (e: unknown) => e instanceof ChatSwarmError && e.code === "OWNERSHIP_CONFLICT"); } finally { cleanup(f); } });

test("task ledger rejects oversized and forged cursor anchors", () => { const f = fixture(); try { const task = f.store.createTask({ swarmId: f.swarm.id, taskKey: "anchor", prompt: "p" }).task; assert.throws(() => f.store.listTaskLedger(f.swarm.id, "x".repeat(1025)), (e: unknown) => e instanceof ChatSwarmError && e.code === "INVALID_INPUT"); const forged = Buffer.from(JSON.stringify({ swarmId: f.swarm.id, createdAt: task.createdAt, taskId: "missing", rowid: 1 })).toString("base64url"); assert.throws(() => f.store.listTaskLedger(f.swarm.id, forged), (e: unknown) => e instanceof ChatSwarmError && e.code === "INVALID_INPUT"); assert.throws(() => f.store.listTaskLedger(f.swarm.id, ""), (e: unknown) => e instanceof ChatSwarmError && e.code === "INVALID_INPUT"); } finally { cleanup(f); } });

test("targeted busy queues are isolated and FIFO per worker", () => { const f = fixture(); const b = f.store.createWorker({ swarmId: f.swarm.id, label: "b", runtimeKind: "mcp_peer" }); try { const activeA = f.store.dispatchTaskAtomic({ swarmId: f.swarm.id, taskKey: "active-a", prompt: "p", preferredWorkerId: f.worker.id }); const activeB = f.store.dispatchTaskAtomic({ swarmId: f.swarm.id, taskKey: "active-b", prompt: "p", preferredWorkerId: b.id }); const queued = ["a1", "a2", "b1", "b2"].map((taskKey) => f.store.dispatchTaskAtomic({ swarmId: f.swarm.id, taskKey, prompt: "p", preferredWorkerId: taskKey.startsWith("a") ? f.worker.id : b.id }, 10)); const sqlite = (f.store as unknown as { sqlite: { prepare: (sql: string) => { run: (...args: unknown[]) => void } } }).sqlite; sqlite.prepare("update chat_swarm_tasks set created_at=? where id in (?,?,?,?)").run("2020-01-01T00:00:00.000Z", ...queued.map((task) => task.id)); assert.deepEqual(queued.map((task) => task.lifecycleState), ["QUEUED", "QUEUED", "QUEUED", "QUEUED"]); assert.equal(f.store.listAttempts(queued[0]!.id).length, 0); f.store.submitResult(activeA.id, f.worker.id, "done-a"); f.store.submitResult(activeB.id, b.id, "done-b"); assert.equal(f.store.claimNextQueuedTaskAtomic(f.worker.id)?.taskKey, "a1"); assert.equal(f.store.claimNextQueuedTaskAtomic(b.id)?.taskKey, "b1"); f.store.submitResult(queued[0]!.id, f.worker.id, "a1-result"); f.store.submitResult(queued[2]!.id, b.id, "b1-result"); assert.equal(f.store.claimNextQueuedTaskAtomic(f.worker.id)?.taskKey, "a2"); assert.equal(f.store.claimNextQueuedTaskAtomic(b.id)?.taskKey, "b2"); assert.equal(f.store.getTask(queued[1]!.id)?.assignedWorkerId, f.worker.id); assert.equal(f.store.getTask(queued[3]!.id)?.assignedWorkerId, b.id); } finally { cleanup(f); } });

test("replay remains one task and one attempt across every lifecycle state", () => { const f = fixture(); try { const input = { swarmId: f.swarm.id, taskKey: "replay-all", prompt: "p", preferredWorkerId: f.worker.id }; const task = f.store.dispatchTaskAtomic(input); const replayClaimed = f.store.dispatchTaskAtomic(input); assert.equal(replayClaimed.id, task.id); assert.equal(f.store.listAttempts(task.id).length, 1); f.store.startTask(task.id, f.worker.id); assert.equal(f.store.dispatchTaskAtomic(input).lifecycleState, "RUNNING"); assert.equal(f.store.listAttempts(task.id).length, 1); const ready = f.store.submitResult(task.id, f.worker.id, "result"); assert.equal(f.store.dispatchTaskAtomic(input).lifecycleState, "RESULT_READY"); assert.equal(f.store.listAttempts(task.id).length, 1); assert.equal(f.store.collectTask(task.id).lifecycleState, "COLLECTED"); assert.equal(f.store.dispatchTaskAtomic(input).id, task.id); assert.equal(f.store.listAttempts(task.id).length, 1); assert.equal(ready.result, "result"); assert.throws(() => f.store.dispatchTaskAtomic({ ...input, prompt: "changed" }), (e: unknown) => e instanceof ChatSwarmError && e.code === "REPLAY_CONFLICT"); } finally { cleanup(f); } });

test("restart reconciles active work without claiming unrelated targeted queue", () => { const f = fixture(); try { const active = f.store.dispatchTaskAtomic({ swarmId: f.swarm.id, taskKey: "active-restart", prompt: "p", preferredWorkerId: f.worker.id }); const queued = f.store.dispatchTaskAtomic({ swarmId: f.swarm.id, taskKey: "queued-restart", prompt: "q", preferredWorkerId: f.worker.id }); assert.equal(queued.lifecycleState, "QUEUED"); f.store.close(); const reopened = new ChatSwarmStore(f.root); reopened.recoverAfterRestart(); assert.equal(reopened.getTask(active.id)?.lifecycleState, "RECONCILE_REQUIRED"); assert.equal(reopened.getTask(queued.id)?.lifecycleState, "QUEUED"); assert.equal(reopened.listAttempts(queued.id).length, 0); assert.equal(reopened.listTaskLedger(f.swarm.id, undefined, 100).tasks.map((task) => task.taskKey).includes("queued-restart"), true); reopened.close(); } finally { rmSync(f.root, { recursive: true, force: true }); } });

test("inconsistent busy pointer fails closed and rolls back new task", () => { const f = fixture(); try { const foreign = f.store.createSwarm({ ownerIdentity: "foreign-owner", workerLimit: 1 }); const foreignTask = f.store.createTask({ swarmId: foreign.id, taskKey: "foreign-task", prompt: "p" }).task; const sqlite = (f.store as unknown as { sqlite: { prepare: (sql: string) => { run: (...args: unknown[]) => void } } }).sqlite; sqlite.prepare("update chat_swarm_workers set lifecycle_state='BUSY', current_task_id=? where id=?").run(foreignTask.id, f.worker.id); assert.throws(() => f.store.dispatchTaskAtomic({ swarmId: f.swarm.id, taskKey: "should-rollback", prompt: "p", preferredWorkerId: f.worker.id }), (e: unknown) => e instanceof ChatSwarmError && e.code === "OWNERSHIP_CONFLICT"); assert.equal(f.store.getTaskByKey(f.swarm.id, "should-rollback"), undefined); } finally { cleanup(f); } });
