import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { ChatSwarmCarrierManager, type CarrierCallInput, type ChatSwarmCarrierAdapter } from "./chat-swarm-carrier.js";
import { ChatSwarmCoordinator } from "./chat-swarm-coordinator.js";
import { ChatSwarmStore } from "./chat-swarm-store.js";

class FakeAdapter implements ChatSwarmCarrierAdapter {
  readonly kind = "fake"; calls = 0; mode: "ready" | "unknown" | "unsupported" = "ready"; entered?: () => void; block = false; resume?: () => void;
  capabilities(): ReturnType<ChatSwarmCarrierAdapter["capabilities"]> { return { boundedWait: "UNSUPPORTED", eventWake: "SUPPORTED", resultReadback: "SUPPORTED", durableReplay: "SUPPORTED" }; }
  async ensureExisting(input: CarrierCallInput) { this.calls++; this.entered?.(); if (this.block) await new Promise<void>((resolve) => { this.resume = resolve; }); if (this.mode === "unknown") return { disposition: "UNKNOWN" as const, operationId: input.operationId, swarmId: input.swarmId, workerId: input.workerId, expectedEpoch: input.expectedEpoch, carrierKind: input.carrierKind, carrierFingerprint: input.carrierFingerprint, remoteMayContinue: true }; if (this.mode === "unsupported") return { disposition: "UNSUPPORTED" as const, operationId: input.operationId, swarmId: input.swarmId, workerId: input.workerId, expectedEpoch: input.expectedEpoch, carrierKind: input.carrierKind, carrierFingerprint: input.carrierFingerprint, remoteMayContinue: false }; return { disposition: "READY" as const, operationId: input.operationId, swarmId: input.swarmId, workerId: input.workerId, expectedEpoch: input.expectedEpoch, carrierKind: input.carrierKind, carrierFingerprint: input.carrierFingerprint, remoteMayContinue: false }; }
  async wake(input: CarrierCallInput) { this.calls++; if (this.mode === "unknown") throw new Error("lost acknowledgement"); return { disposition: "DELIVERED" as const, operationId: input.operationId, swarmId: input.swarmId, workerId: input.workerId, expectedEpoch: input.expectedEpoch, taskId: input.taskId, attemptId: input.attemptId, carrierKind: input.carrierKind, carrierFingerprint: input.carrierFingerprint, remoteMayContinue: false }; }
}

function fixture() { const root = mkdtempSync(join(tmpdir(), "devspace-carrier-g1-")); const store = new ChatSwarmStore(root); const coordinator = new ChatSwarmCoordinator(store); const owner = { "openai/session": "owner" }; const swarm = coordinator.createSwarm(owner, { workerLimit: 3 }); const worker = store.createWorker({ swarmId: swarm.id, label: "peer", runtimeKind: "mcp_peer", carrierConversationFingerprint: "a".repeat(64) }); return { root, store, coordinator, owner, swarm, worker }; }
function cleanup(f: ReturnType<typeof fixture>) { f.store.close(); rmSync(f.root, { recursive: true, force: true }); }

test("identical ensure replay across managers uses one durable operation", async () => { const f = fixture(); const adapter = new FakeAdapter(); const secondStore = new ChatSwarmStore(f.root); try { const one = new ChatSwarmCarrierManager(f.store, f.coordinator, adapter); const two = new ChatSwarmCarrierManager(secondStore, new ChatSwarmCoordinator(secondStore), adapter); const [a, b] = await Promise.all([one.ensure(f.owner, f.swarm.id, 1, "b".repeat(64)), two.ensure(f.owner, f.swarm.id, 1, "b".repeat(64))]); assert.equal(a[0]?.state, "SUCCEEDED"); assert.equal(b[0]?.operationId, a[0]?.operationId); assert.equal(adapter.calls, 1); } finally { secondStore.close(); cleanup(f); } });

test("restart fences intent before acknowledgement and late completion cannot override it", async () => { const f = fixture(); const adapter = new FakeAdapter(); let entered!: () => void; const reached = new Promise<void>((resolve) => { entered = resolve; }); adapter.entered = entered; adapter.block = true; try { const manager = new ChatSwarmCarrierManager(f.store, f.coordinator, adapter, 1000); const pending = manager.ensure(f.owner, f.swarm.id, 1, "c".repeat(64)); await reached; const restarted = new ChatSwarmStore(f.root); try { assert.equal(restarted.fenceCarrierOperations(), 1); const row = (restarted as any).sqlite.prepare("select state from chat_swarm_carrier_operations").get() as { state: string }; assert.equal(row.state, "RECONCILE_REQUIRED"); adapter.resume?.(); const result = await pending; assert.equal(result[0]?.state, "RECONCILE_REQUIRED"); } finally { restarted.close(); } } finally { cleanup(f); } });

test("missing admitted capacity never invokes adapter", async () => { const f = fixture(); const adapter = new FakeAdapter(); try { const manager = new ChatSwarmCarrierManager(f.store, f.coordinator, adapter); const result = await manager.ensure(f.owner, f.swarm.id, 2, "d".repeat(64)); assert.equal(result[0]?.blocker, "ADMISSION_REQUIRED"); assert.equal(adapter.calls, 0); } finally { cleanup(f); } });

test("wake binds exact task attempt and preserves canonical task state", async () => { const f = fixture(); const adapter = new FakeAdapter(); try { const manager = new ChatSwarmCarrierManager(f.store, f.coordinator, adapter); const task = f.store.createTask({ swarmId: f.swarm.id, taskKey: "wake", prompt: "p" }).task; f.store.claimTask(task.id, f.worker.id); const before = f.store.getTask(task.id); const result = await manager.wake(f.owner, { swarmId: f.swarm.id, workerId: f.worker.id, expectedEpoch: 0, taskId: task.id, adapterConfigHash: "e".repeat(64) }); assert.equal(result.state, "SUCCEEDED"); assert.deepEqual(f.store.getTask(task.id), before); assert.ok(result.attemptId); } finally { cleanup(f); } });

test("unknown delivery is pinned and never blindly retried", async () => { const f = fixture(); const adapter = new FakeAdapter(); adapter.mode = "unknown"; try { const manager = new ChatSwarmCarrierManager(f.store, f.coordinator, adapter); const result = await manager.wake(f.owner, { swarmId: f.swarm.id, workerId: f.worker.id, expectedEpoch: 0, adapterConfigHash: "f".repeat(64) }); assert.equal(result.state, "RECONCILE_REQUIRED"); const replay = await manager.wake(f.owner, { swarmId: f.swarm.id, workerId: f.worker.id, expectedEpoch: 0, adapterConfigHash: "f".repeat(64) }); assert.equal(replay.operationId, result.operationId); assert.equal(adapter.calls, 1); } finally { cleanup(f); } });

test("slot material conflict and owner or epoch denial fail closed", async () => { const f = fixture(); const adapter = new FakeAdapter(); try { const manager = new ChatSwarmCarrierManager(f.store, f.coordinator, adapter); await manager.ensure(f.owner, f.swarm.id, 1, "1".repeat(64)); await assert.rejects(manager.ensure(f.owner, f.swarm.id, 1, "2".repeat(64)), /different material/); await assert.rejects(manager.wake({ "openai/session": "other" }, { swarmId: f.swarm.id, workerId: f.worker.id, expectedEpoch: 0, adapterConfigHash: "3".repeat(64) }), /does not own/); await assert.rejects(manager.wake(f.owner, { swarmId: f.swarm.id, workerId: f.worker.id, expectedEpoch: 1, adapterConfigHash: "3".repeat(64) }), /epoch changed/); } finally { cleanup(f); } });

test("unsupported event wake is explicit and does not create a carrier effect", async () => { const f = fixture(); const adapter = new FakeAdapter(); adapter.capabilities = () => ({ boundedWait: "SUPPORTED", eventWake: "UNSUPPORTED", resultReadback: "SUPPORTED", durableReplay: "SUPPORTED" }); try { const manager = new ChatSwarmCarrierManager(f.store, f.coordinator, adapter); await assert.rejects(manager.wake(f.owner, { swarmId: f.swarm.id, workerId: f.worker.id, expectedEpoch: 0, adapterConfigHash: "4".repeat(64) }), /UNSUPPORTED/); assert.equal(adapter.calls, 0); } finally { cleanup(f); } });

test("busy workers are protected from ensure side effects", async () => { const f = fixture(); const adapter = new FakeAdapter(); try { const task = f.store.createTask({ swarmId: f.swarm.id, taskKey: "busy", prompt: "p" }).task; f.store.claimTask(task.id, f.worker.id); const result = await new ChatSwarmCarrierManager(f.store, f.coordinator, adapter).ensure(f.owner, f.swarm.id, 1, "b".repeat(64)); assert.equal(result[0]?.blocker, "BUSY_WORKER_PROTECTED"); assert.equal(adapter.calls, 0); } finally { cleanup(f); } });
test("mismatched wake evidence is fenced", async () => { const f = fixture(); const adapter = new FakeAdapter(); const original = adapter.wake.bind(adapter); adapter.wake = async (input) => ({ ...(await original(input)), taskId: "wrong-task", attemptId: "wrong-attempt" }); try { const task = f.store.createTask({ swarmId: f.swarm.id, taskKey: "mismatch", prompt: "p" }).task; f.store.claimTask(task.id, f.worker.id); const result = await new ChatSwarmCarrierManager(f.store, f.coordinator, adapter).wake(f.owner, { swarmId: f.swarm.id, workerId: f.worker.id, expectedEpoch: 0, taskId: task.id, adapterConfigHash: "e".repeat(64) }); assert.equal(result.state, "RECONCILE_REQUIRED"); } finally { cleanup(f); } });
test("status retains reconciled workers after restart", async () => { const f = fixture(); const adapter = new FakeAdapter(); adapter.block = true; try { const manager = new ChatSwarmCarrierManager(f.store, f.coordinator, adapter, 10); const pending = manager.ensure(f.owner, f.swarm.id, 1, "b".repeat(64)); await new Promise((resolve) => setTimeout(resolve, 1)); const reopened = new ChatSwarmStore(f.root); reopened.fenceCarrierOperations(); const status = new ChatSwarmCarrierManager(reopened, new ChatSwarmCoordinator(reopened), adapter).status(f.owner, f.swarm.id); assert.equal(status.workers[0]?.state, "RECONCILE_REQUIRED"); await pending.catch(() => undefined); reopened.close(); } finally { cleanup(f); } });
test("targeted queued worker is protected from ensure effects", async () => { const f = fixture(); const adapter = new FakeAdapter(); try { f.store.createTask({ swarmId: f.swarm.id, taskKey: "targeted", prompt: "p", preferredWorkerId: f.worker.id }); const result = await new ChatSwarmCarrierManager(f.store, f.coordinator, adapter).ensure(f.owner, f.swarm.id, 1, "b".repeat(64)); assert.equal(result[0]?.blocker, "TARGETED_WORKER_PROTECTED"); assert.equal(adapter.calls, 0); } finally { cleanup(f); } });
