import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { ChatSwarmError } from "./chat-swarm-contract.js";
import { ChatSwarmCoordinator } from "./chat-swarm-coordinator.js";
import { ChatSwarmStore } from "./chat-swarm-store.js";

function fixture() { const root = mkdtempSync(join(tmpdir(), "devspace-swarm-protocol-")); const store = new ChatSwarmStore(root); const coordinator = new ChatSwarmCoordinator(store); const owner = { "openai/session": "owner-conversation" }; const workerMeta = { "openai/session": "worker-conversation" }; const swarm = coordinator.createSwarm(owner, { workerLimit: 2 }); return { root, store, coordinator, owner, workerMeta, swarm }; }
function cleanup(f: { root: string; store: ChatSwarmStore }) { f.store.close(); rmSync(f.root, { recursive: true, force: true }); }

test("owner-bound swarm creation, idempotent worker join, deterministic dispatch and own submit", () => { const f = fixture(); try { const worker = f.coordinator.joinWorker(f.workerMeta, f.swarm.id, { id: "worker-a", label: "peer", runtimeKind: "mcp_peer" }); assert.equal(f.coordinator.joinWorker(f.workerMeta, f.swarm.id, { id: "worker-a", label: "peer", runtimeKind: "mcp_peer" }).id, worker.id); const task = f.coordinator.dispatch(f.owner, { swarmId: f.swarm.id, taskKey: "t1", prompt: "hello" }); assert.equal(task.assignedWorkerId, worker.id); assert.throws(() => f.coordinator.submit({ "openai/session": "other" }, worker.id, task.id, "result"), (e: unknown) => e instanceof ChatSwarmError && e.code === "OWNERSHIP_CONFLICT"); assert.equal(f.coordinator.submit(f.workerMeta, worker.id, task.id, "result").result, "result"); } finally { cleanup(f); } });

test("controller and worker identity substitution, conflicting carrier binding, and changed replay fail closed", () => { const f = fixture(); try { assert.throws(() => f.coordinator.dispatch({ "openai/session": "other" }, { swarmId: f.swarm.id, taskKey: "x", prompt: "p" }), (e: unknown) => e instanceof ChatSwarmError && e.code === "OWNERSHIP_CONFLICT"); f.coordinator.joinWorker(f.workerMeta, f.swarm.id, { id: "worker-a", label: "peer", runtimeKind: "mcp_peer" }); assert.throws(() => f.coordinator.joinWorker(f.workerMeta, f.swarm.id, { id: "worker-b", label: "peer", runtimeKind: "mcp_peer" }), (e: unknown) => e instanceof ChatSwarmError && e.code === "OWNERSHIP_CONFLICT"); f.coordinator.dispatch(f.owner, { swarmId: f.swarm.id, taskKey: "replay", prompt: "one" }); assert.throws(() => f.coordinator.dispatch(f.owner, { swarmId: f.swarm.id, taskKey: "replay", prompt: "two" }), (e: unknown) => e instanceof ChatSwarmError && e.code === "REPLAY_CONFLICT"); } finally { cleanup(f); } });

test("controller actions cannot cross swarm ownership and active cancel remains uncertain", () => { const f = fixture(); try { const ownerB = { "openai/session": "owner-b" }; const workerBMeta = { "openai/session": "worker-b" }; const swarmB = f.coordinator.createSwarm(ownerB, { workerLimit: 1 }); const worker = f.coordinator.joinWorker(f.workerMeta, f.swarm.id, { id: "worker-a", label: "peer", runtimeKind: "mcp_peer" }); const foreignWorker = f.coordinator.joinWorker(workerBMeta, swarmB.id, { id: "worker-b", label: "peer", runtimeKind: "mcp_peer" }); const foreignTask = f.coordinator.dispatch(ownerB, { swarmId: swarmB.id, taskKey: "foreign", prompt: "p" }); assert.throws(() => f.coordinator.collect(f.owner, f.swarm.id, foreignTask.id), (e: unknown) => e instanceof ChatSwarmError && e.code === "OWNERSHIP_CONFLICT"); assert.throws(() => f.coordinator.reconcile(f.owner, f.swarm.id, foreignTask.id, "FAILED"), (e: unknown) => e instanceof ChatSwarmError && e.code === "OWNERSHIP_CONFLICT"); const ownTask = f.coordinator.dispatch(f.owner, { swarmId: f.swarm.id, taskKey: "cancel", prompt: "p" }); assert.equal(f.coordinator.cancel(f.owner, f.swarm.id, ownTask.id).lifecycleState, "CANCEL_REQUESTED"); assert.equal(f.store.getWorker(worker.id)?.currentTaskId, ownTask.id); assert.equal(f.store.getWorker(foreignWorker.id)?.currentTaskId, foreignTask.id); } finally { cleanup(f); } });

test("peer join and lease validation reject unsupported adapters, raw fingerprints, and non-UTC or unbounded times", () => { const f = fixture(); try { assert.throws(() => f.coordinator.joinWorker({ "openai/session": "raw-adapter" }, f.swarm.id, { label: "bad", runtimeKind: "openai_api", sessionIdentityFingerprint: "a".repeat(64) }), (e: unknown) => e instanceof ChatSwarmError && e.code === "INVALID_INPUT"); assert.throws(() => f.coordinator.joinWorker({ "openai/session": "raw-peer" }, f.swarm.id, { label: "bad", runtimeKind: "mcp_peer", sessionIdentityFingerprint: "raw" }), (e: unknown) => e instanceof ChatSwarmError && e.code === "INVALID_INPUT"); const worker = f.coordinator.joinWorker({ "openai/session": "valid" }, f.swarm.id, { label: "peer", runtimeKind: "mcp_peer" }); assert.throws(() => f.coordinator.checkpoint({ "openai/session": "valid" }, worker.id, worker.continuationEpoch, "2030-01-01T00:00:00.000Z", {}), (e: unknown) => e instanceof ChatSwarmError && e.code === "INVALID_INPUT"); assert.throws(() => f.coordinator.checkpoint({ "openai/session": "valid" }, worker.id, worker.continuationEpoch, "2999-01-01T00:00:00+00:00", {}), (e: unknown) => e instanceof ChatSwarmError && e.code === "INVALID_INPUT"); } finally { cleanup(f); } });

test("targeted and first-available dispatch are deterministic and lease expiry reconciles without retry", () => { const f = fixture(); try { const first = f.coordinator.joinWorker({ "openai/session": "worker-z" }, f.swarm.id, { id: "worker-z", label: "z", runtimeKind: "mcp_peer" }); const second = f.coordinator.joinWorker({ "openai/session": "worker-a" }, f.swarm.id, { id: "worker-a", label: "a", runtimeKind: "mcp_peer" }); const targeted = f.coordinator.dispatch(f.owner, { swarmId: f.swarm.id, taskKey: "targeted", prompt: "p", preferredWorkerId: first.id }); assert.equal(targeted.assignedWorkerId, first.id); const next = f.coordinator.nextTask({ "openai/session": "worker-z" }, first.id); assert.equal(next?.id, targeted.id); const lease = new Date(Date.now() + 10_000).toISOString(); f.coordinator.checkpoint({ "openai/session": "worker-z" }, first.id, first.continuationEpoch, lease, { cursor: "c" }); const expired = f.coordinator.expireLease(first.id, new Date(Date.now() + 20_000).toISOString()); assert.equal(expired?.lifecycleState, "RECONCILE_REQUIRED"); assert.equal(f.coordinator.nextTask({ "openai/session": "worker-z" }, first.id), undefined); const available = f.coordinator.dispatch(f.owner, { swarmId: f.swarm.id, taskKey: "available", prompt: "p" }); assert.equal(available.assignedWorkerId, second.id); } finally { cleanup(f); } });

test("task ledger is owner-only and survives durable store close and reopen", () => { const f = fixture(); let reopenedStore: ChatSwarmStore | undefined; try { const task = f.coordinator.dispatch(f.owner, { swarmId: f.swarm.id, taskKey: "recover", prompt: "secret" }); f.store.close(); reopenedStore = new ChatSwarmStore(f.root); reopenedStore.recoverAfterRestart(); const reopened = new ChatSwarmCoordinator(reopenedStore); assert.equal(reopened.listTasks(f.owner, f.swarm.id, undefined, 10).tasks[0]?.taskId, task.id); assert.throws(() => reopened.listTasks({ "openai/session": "other" }, f.swarm.id), (e: unknown) => e instanceof ChatSwarmError && e.code === "OWNERSHIP_CONFLICT"); } finally { reopenedStore?.close(); rmSync(f.root, { recursive: true, force: true }); } });

test("task ledger denies a different swarm owner from crossing swarm boundaries", () => { const f = fixture(); try { const otherOwner = { "openai/session": "other-owner" }; const other = f.coordinator.createSwarm(otherOwner, { workerLimit: 1 }); assert.throws(() => f.coordinator.listTasks(otherOwner, f.swarm.id), (e: unknown) => e instanceof ChatSwarmError && e.code === "OWNERSHIP_CONFLICT"); assert.throws(() => f.coordinator.listTasks(f.owner, other.id), (e: unknown) => e instanceof ChatSwarmError && e.code === "OWNERSHIP_CONFLICT"); } finally { cleanup(f); } });
