import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawn } from "node:child_process";
import test from "node:test";
import Database from "better-sqlite3";
import { ControlPlaneOwnershipError, ControlPlaneOwnershipStore, initializeControlPlaneOwnershipDatabase, type GrantEvidenceReference } from "./control-plane-ownership.js";
import { getCompletionMatrixRow, upsertCompletionMatrixRow } from "./current-completion-matrix.js";

const grant: GrantEvidenceReference = { repository: "owner/repo", goal: "goal", coordinatorThread: "coord", evidenceHash: "hash" };
const context = (thread: string) => ({ thread });
const options = { resolveOwnerContext: (value: unknown) => { const thread = (value as { thread?: unknown })?.thread; return typeof thread === "string" ? { ownerThread: thread } : undefined; }, verifyGrantEvidence: (value: GrantEvidenceReference) => value.repository === "owner/repo" && value.goal === "goal" && value.coordinatorThread === "coord" && value.evidenceHash === "hash" };
function input(scope = ["/repo/src/a"]): Parameters<ControlPlaneOwnershipStore["acquire"]>[1] { return { repositoryKey: "owner/repo", resourceKind: "checkout", resourceId: "main", resource: "checkout", operation: "write", scope, baseRevision: "sha-a", expiresAt: new Date(Date.now() + 60_000).toISOString(), idempotencyKey: `key-${scope.join("-")}`, grant }; }
function db() { const sqlite = new Database(":memory:"); initializeControlPlaneOwnershipDatabase(sqlite); return sqlite; }

test("acquire/assert/release requires verified grant and trusted owner context", () => { const sqlite = db(); const store = new ControlPlaneOwnershipStore(sqlite, options); try { const lease = store.acquire(context("owner"), input()); assert.equal(store.assertHeld(context("owner"), lease.leaseId, 1, "write", "sha-a").ownerThread, "owner"); assert.throws(() => store.acquire({ thread: "attacker" }, { ...input(), grant: { ...grant, evidenceHash: "forged" } }), (error: unknown) => error instanceof ControlPlaneOwnershipError && error.code === "AUTHORITY_REQUIRED"); assert.throws(() => store.assertHeld({}, lease.leaseId, 1, "write", "sha-a"), (error: unknown) => error instanceof ControlPlaneOwnershipError && error.code === "AUTHORITY_REQUIRED"); const released = store.release(context("owner"), lease.leaseId, 1); assert.equal(released.terminalState, "released"); assert.throws(() => store.assertHeld(context("owner"), lease.leaseId, 2, "write", "sha-a"), ControlPlaneOwnershipError); } finally { sqlite.close(); } });

test("ancestor and descendant scopes conflict; expired unresolved lease cannot be stolen", () => { const sqlite = db(); const store = new ControlPlaneOwnershipStore(sqlite, options); try { const lease = store.acquire(context("one"), input(["/repo"])); assert.throws(() => store.acquire(context("two"), { ...input(["/repo/src"]), idempotencyKey: "descendant" }), (error: unknown) => error instanceof ControlPlaneOwnershipError && error.code === "OWNERSHIP_CONFLICT"); const expired = { ...lease, expiresAt: new Date(Date.now() - 1).toISOString() }; sqlite.prepare("update control_plane_resource_leases set expires_at=? where lease_id=?").run(expired.expiresAt, lease.leaseId); assert.throws(() => store.acquire(context("three"), { ...input(["/repo"]), idempotencyKey: "expired-steal" }), (error: unknown) => error instanceof ControlPlaneOwnershipError && error.code === "OWNERSHIP_CONFLICT"); } finally { sqlite.close(); } });

test("handoff is atomic and stale owner/version cannot mutate", () => { const sqlite = db(); const store = new ControlPlaneOwnershipStore(sqlite, options); try { const lease = store.acquire(context("from"), input()); const receipt = store.handoff(context("from"), lease.leaseId, 1, context("to"), { resource: "checkout", candidateRevision: "sha-b", liveOperation: "op", liveHandle: "handle", forbiddenOverlap: ["/repo"], tests: ["race"], evidence: ["evidence"], remainingGap: "none", nextGate: "review", expiresAt: lease.expiresAt }); assert.equal(receipt.newVersion, 2); assert.throws(() => store.assertHeld(context("from"), lease.leaseId, 1, "write", "sha-a"), (error: unknown) => error instanceof ControlPlaneOwnershipError && error.code === "CAS_CONFLICT"); assert.equal(store.assertHeld(context("to"), lease.leaseId, 2, "write", "sha-a").ownerThread, "to"); } finally { sqlite.close(); } });

test("operation pin closes the release/handoff TOCTOU window", () => { const sqlite = db(); const store = new ControlPlaneOwnershipStore(sqlite, options); try { const lease = store.acquire(context("from"), input()); const pinned = store.beginOperation(context("from"), lease.leaseId, 1, "run-1"); assert.equal(pinned.operationHandle, "run-1"); assert.throws(() => store.release(context("from"), lease.leaseId, 2), (error: unknown) => error instanceof ControlPlaneOwnershipError && error.code === "OWNERSHIP_CONFLICT"); assert.throws(() => store.handoff(context("from"), lease.leaseId, 2, context("to"), { resource: "checkout", candidateRevision: "sha-b", liveOperation: "op", liveHandle: "wrong", forbiddenOverlap: ["/repo"], tests: [], evidence: [], remainingGap: "none", nextGate: "review", expiresAt: lease.expiresAt }), (error: unknown) => error instanceof ControlPlaneOwnershipError && error.code === "CAS_CONFLICT"); const receipt = store.handoff(context("from"), lease.leaseId, 2, context("to"), { resource: "checkout", candidateRevision: "sha-b", liveOperation: "op", liveHandle: "run-1", forbiddenOverlap: ["/repo"], tests: [], evidence: [], remainingGap: "none", nextGate: "review", expiresAt: lease.expiresAt }); assert.equal(receipt.liveHandle, "run-1"); const finished = store.finishOperation(context("to"), lease.leaseId, 3, "run-1"); assert.equal(finished.operationState, "finished"); } finally { sqlite.close(); } });

test("repository aliases canonicalize before overlap checks", () => { const sqlite = db(); const store = new ControlPlaneOwnershipStore(sqlite, options); try { store.acquire(context("one"), input(["/repo/src"])); assert.throws(() => store.acquire(context("two"), { ...input(["/repo/src/child"]), repositoryKey: "OWNER/REPO", idempotencyKey: "canonical-alias" }), (error: unknown) => error instanceof ControlPlaneOwnershipError && error.code === "OWNERSHIP_CONFLICT"); assert.throws(() => store.acquire(context("two"), { ...input(["repo/src"]), idempotencyKey: "relative" }), (error: unknown) => error instanceof ControlPlaneOwnershipError && error.code === "INVALID_INPUT"); } finally { sqlite.close(); } });

test("root and trailing-slash scopes cannot bypass overlap", () => { const sqlite = db(); const store = new ControlPlaneOwnershipStore(sqlite, options); try { store.acquire(context("one"), input(["/"])); assert.throws(() => store.acquire(context("two"), { ...input(["/repo"]), idempotencyKey: "root-child" }), (error: unknown) => error instanceof ControlPlaneOwnershipError && error.code === "OWNERSHIP_CONFLICT"); } finally { sqlite.close(); } });

test("grant evidence index uses composite key and CAS across restart", () => { const sqlite = db(); const indexOptions = { ...options, verifyGrantEvidence: () => true }; const store = new ControlPlaneOwnershipStore(sqlite, indexOptions); const ref = { ...grant, evidenceHash: "first" }; try { assert.equal(store.putGrantEvidence(ref, 0).version, 1); assert.throws(() => store.putGrantEvidence({ ...ref, evidenceHash: "stale" }, 0), (error: unknown) => error instanceof ControlPlaneOwnershipError && error.code === "CAS_CONFLICT"); assert.equal(store.putGrantEvidence({ ...ref, evidenceHash: "second" }, 1).version, 2); assert.equal(store.getGrantEvidence(ref.repository, ref.goal, ref.coordinatorThread)?.evidenceHash, "second"); const reopened = new ControlPlaneOwnershipStore(sqlite, indexOptions); assert.equal(reopened.getGrantEvidence(ref.repository, ref.goal, ref.coordinatorThread)?.version, 2); } finally { sqlite.close(); } });

test("grant evidence index rejects missing authoritative verifier", () => { const sqlite = db(); const store = new ControlPlaneOwnershipStore(sqlite, { resolveOwnerContext: options.resolveOwnerContext }); try { assert.throws(() => store.putGrantEvidence(grant, 0), (error: unknown) => error instanceof ControlPlaneOwnershipError && error.code === "AUTHORITY_REQUIRED"); } finally { sqlite.close(); } });

test("trailing slash cannot bypass descendant overlap", () => { const sqlite = db(); const store = new ControlPlaneOwnershipStore(sqlite, options); try { store.acquire(context("one"), input(["/repo/"])); assert.throws(() => store.acquire(context("two"), { ...input(["/repo/src"]), idempotencyKey: "slash-child" }), (error: unknown) => error instanceof ControlPlaneOwnershipError && error.code === "OWNERSHIP_CONFLICT"); } finally { sqlite.close(); } });

test("completion matrix uses opaque revision plus expected version CAS", () => { const sqlite = db(); initializeControlPlaneOwnershipDatabase(sqlite); try { const first = upsertCompletionMatrixRow(sqlite, { goal: "goal", layer: "Implementation", source: "receipt", revision: "0000dead", status: "已實作", freshness: "fresh", gap: "" }, 0); assert.equal(first.version, 1); const second = upsertCompletionMatrixRow(sqlite, { goal: "goal", layer: "Implementation", source: "receipt", revision: "00000001", status: "PASS", freshness: "fresh", gap: "" }, 1, "0000dead"); assert.equal(second.version, 2); assert.throws(() => upsertCompletionMatrixRow(sqlite, { ...second, status: "FAIL" }, 1, "00000001"), (error: unknown) => error instanceof ControlPlaneOwnershipError && error.code === "CAS_CONFLICT"); assert.equal(getCompletionMatrixRow(sqlite, "goal", "Implementation")?.revision, "00000001"); } finally { sqlite.close(); } });

test("two independent processes race for one overlapping lease", async () => { const root = mkdtempSync(join(tmpdir(), "devspace-control-plane-race-")); const databasePath = join(root, "state.sqlite"); const script = `import Database from "better-sqlite3"; import { ControlPlaneOwnershipStore } from "./src/control-plane-ownership.ts"; const db = new Database(process.argv[1]); const o={resolveOwnerContext:(v)=>({ownerThread:String(v)}),verifyGrantEvidence:()=>true}; const s=new ControlPlaneOwnershipStore(db,o); try { const l=s.acquire(process.argv[2],{repositoryKey:"owner/repo",resourceKind:"checkout",resourceId:"main",resource:"checkout",operation:"write",scope:["/repo/src"],baseRevision:"sha",expiresAt:new Date(Date.now()+60000).toISOString(),idempotencyKey:process.argv[2],grant:{repository:"owner/repo",goal:"g",coordinatorThread:"c",evidenceHash:"h"}}); console.log("won:"+l.ownerThread); } catch(e) { console.log("lost:"+(e.code||"error")); } finally { db.close(); }`;
  const run = (owner: string) => new Promise<string>((resolve) => { const child = spawn(process.execPath, ["--import", "tsx", "-e", script, databasePath, owner], { cwd: process.cwd() }); let out = ""; child.stdout.on("data", (chunk) => { out += chunk; }); child.on("close", () => resolve(out.trim())); });
  try { const results = await Promise.all([run("one"), run("two")]); assert.equal(results.filter((value) => value.startsWith("won:")).length, 1); assert.equal(results.filter((value) => value.startsWith("lost:")).length, 1); } finally { rmSync(root, { recursive: true, force: true }); } });
