import type Database from "better-sqlite3";
import { initializeControlPlaneOwnershipDatabase, ControlPlaneOwnershipError } from "./control-plane-ownership.js";

export type CompletionLayer = "Implementation" | "Source verification" | "Integration" | "Install/package" | "Runtime" | "Deployment" | "Native/real entrypoint" | "Authorization";
export type CompletionStatus = "未實作" | "已實作" | "未驗收" | "PASS" | "FAIL" | "未接線" | "已接線" | "未執行" | "未部署" | "已部署" | "READY" | "BLOCKED" | "EXPIRED";
export interface CompletionMatrixRow { goal: string; layer: CompletionLayer; source: string; revision: string; status: CompletionStatus; freshness: string; gap: string; version: number; updatedAt: string; }

export function initializeCompletionMatrixDatabase(sqlite: Database.Database): void { initializeControlPlaneOwnershipDatabase(sqlite); }
export function upsertCompletionMatrixRow(sqlite: Database.Database, input: Omit<CompletionMatrixRow, "version" | "updatedAt">, expectedVersion: number, expectedCurrentRevision?: string, now = Date.now()): CompletionMatrixRow {
  if (!input.goal || !input.layer || !input.source || !input.revision || !input.status || !input.freshness) throw new ControlPlaneOwnershipError("INVALID_INPUT", "completion matrix fields are required");
  const tx = sqlite.transaction(() => { const existing = sqlite.prepare("select * from control_plane_completion_matrix where goal=? and layer=?").get(input.goal, input.layer) as Record<string, unknown> | undefined; if (!existing) { if (expectedVersion !== 0 || expectedCurrentRevision !== undefined) throw new ControlPlaneOwnershipError("CAS_CONFLICT", "matrix row does not exist"); sqlite.prepare("insert into control_plane_completion_matrix (goal,layer,source,revision,status,freshness,gap,version,updated_at) values (?,?,?,?,?,?,?,?,?)").run(input.goal, input.layer, input.source, input.revision, input.status, input.freshness, input.gap, 1, new Date(now).toISOString()); } else { if (expectedCurrentRevision === undefined || Number(existing.version) !== expectedVersion || existing.revision !== expectedCurrentRevision) throw new ControlPlaneOwnershipError("CAS_CONFLICT", "matrix version and current revision are both required"); sqlite.prepare("update control_plane_completion_matrix set source=?,revision=?,status=?,freshness=?,gap=?,version=version+1,updated_at=? where goal=? and layer=? and version=? and revision=?").run(input.source, input.revision, input.status, input.freshness, input.gap, new Date(now).toISOString(), input.goal, input.layer, expectedVersion, expectedCurrentRevision); } return row(sqlite.prepare("select * from control_plane_completion_matrix where goal=? and layer=?").get(input.goal, input.layer) as Record<string, unknown>); }); return tx.immediate();
}
function row(value: Record<string, unknown>): CompletionMatrixRow {
  const required = ["goal", "layer", "source", "revision", "status", "freshness", "version", "updated_at"];
  if (required.some((key) => typeof value[key] !== "string" && key !== "version") || !Number.isInteger(Number(value.version)) || Number(value.version) < 1) throw new ControlPlaneOwnershipError("MALFORMED", "completion matrix row is malformed");
  return { goal: String(value.goal), layer: value.layer as CompletionLayer, source: String(value.source), revision: String(value.revision), status: value.status as CompletionStatus, freshness: String(value.freshness), gap: value.gap === null ? "" : String(value.gap ?? ""), version: Number(value.version), updatedAt: String(value.updated_at) };
}
export function getCompletionMatrixRow(sqlite: Database.Database, goal: string, layer: CompletionLayer): CompletionMatrixRow | undefined { const value = sqlite.prepare("select * from control_plane_completion_matrix where goal=? and layer=?").get(goal, layer) as Record<string, unknown> | undefined; return value ? row(value) : undefined; }
